# Generated by Django 3.2.15 on 2022-08-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contactus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('c_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(),
        ),
    ]
