# Generated by Django 3.2.15 on 2022-08-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220830_0521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactUs',
        ),
    ]
